# Generated by Django 4.2.16 on 2024-11-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinfo",
            name="fb_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="ig_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="linkedIn_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="occupation",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="x_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="gender",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
