# Generated by Django 4.2.16 on 2024-11-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_generalinfo_fb_link_generalinfo_ig_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinfo",
            name="bio",
            field=models.TextField(default="text"),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="fb_link",
            field=models.URLField(default="text"),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="gender",
            field=models.CharField(default="text", max_length=6),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="ig_link",
            field=models.URLField(default="text"),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="linkedIn_link",
            field=models.URLField(default="text"),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="occupation",
            field=models.CharField(default="text", max_length=250),
        ),
        migrations.AlterField(
            model_name="generalinfo",
            name="x_link",
            field=models.URLField(default="text"),
        ),
    ]
